# ========================
# Datasource
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/phone_order_api_local_db
spring.datasource.username=${PHONE_ORDER_DB_USERNAME}
spring.datasource.password=${PHONE_ORDER_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ========================
# SQL
# ========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.orm.jdbc.extract=TRACE
