# ========================
# Datasource
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/phone_order_api_dev_db
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver
# ========================
# SQL
# ========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.orm.jdbc.extract=TRACE
