services:
  postgres:
    image: postgres:16
    container_name: phone-order-api-local-db
    environment:
      POSTGRES_DB: phone_order_api_local_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
